# Generated by Django 4.1.4 on 2022-12-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_quote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('thoughts', models.TextField(max_length=2000)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.quote')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
